### ISSUE TITLE
Feature Tracking: Ticket Manager (Phase 1 - Breakdown)

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#610]
# Context 
Hive Process will integrate Stakwork Workflows and automation into the Hive Development Process. This will reduce workload on Product Managers by streamlining creative tasks and automating the drafting of product artefacts and audit tasks.

## Feature: Ticket Manager - Breakdown Tickets

This feature will allow product managers to quickly and efficiently extract information and context from Hive and Github and use it to breakdown tickets into smaller chunks ready for assignment quicker to the Bounty Platform.

Utilising the ticket breakdown workflow will allow us to build out tracking Github issues with context and or take existing tickets that are great, but need to be broken out and to automate the process of detailing out the chunks of work saving time for the Product Manager / Architect persona.

### Solution Sketch
![image](https://github.com/user-attachments/assets/14be8343-641c-48cc-b366-8177f377caf2)

### Wireframes
![image](https://github.com/user-attachments/assets/9e1e3ad6-53bc-44d0-999d-1175e975db13)

#### Workflows:
- [x] [Workflow: Ticket Automation](https://github.com/stakwork/senza-lnd/issues/6567)
- [x] [Workflkow: Ticket Breakdown](https://github.com/stakwork/senza-lnd/issues/6577)

##### Views
- [ ] Ticket Manager View
- [ ] Ticket Brakdown Modal
- [ ] Ticket Plan Viewer

##### Integreation
- [ ] Construct POST Data from backend calls and send POST Request to Stakwork

#### Back End:
- [ ] New Endpoint feature/ticketPlan/ - end point to receive the output of the workflow and update the ticket plan and ticket drafts DB
- [ ] New Endpoint feature/ticketManage/ returns details of all ticket plans and metadata (create data, time, for manage view)
- [ ] New Endpoint feature/ticketPlan/UUID - returns all draft tickets for a ticketPlan UUID 
- [ ] New DB table ticketsDraft - storage of draft tickets with a ticket plan UUID
- [ ] New DB table ticketsPlan - list of ticket plans that include multiple tickets, generated per job
- [ ] New Jobs

### Phase Future (holding area for future phase tickets): 
- [ ] tbd
