### ISSUE TITLE
Feature Tracking: Remove V1 from Bounties App

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#628]
Sphinx Users have been transitioning to a V2 Sphinx App and pubkey infrastructure. 

In order to facilitate communication between bounty hunters, providers we will need all users on Sphinx V2. 

### Tasks:

- [ ] Confirm the correct format to identify V2 pubkeys vs. V1. 
- [ ] Remove from Bounty Selector Lookup
- [ ] Remove from People page
- [ ] RTqnsfer open bounties on v1 Pubkey to V2 Pubkeys
- [ ] Turn off logins via V1 PUbkey
