### ISSUE TITLE
Component - Ticket Editor (text boxes, Save and Ticket Builder) per ticket

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#659]
## Context

We need to create a reusable component for the phase planner page that allows users to create and edit ticket descriptions. This component will:

- Enable dynamic creation of ticket descriptions as part of phase planning
- Automatically manage ticket sequencing and naming
- Persist ticket data to the database
- Provide real-time editing capabilities

This fits into the larger system by supporting the phase planning workflow and maintaining ticket data integrity.

## Task

1. Create a new component for the ticket builder
2. Implement automatic ticket creation on component load
3. Add text area for ticket description editing
4. Implement database integration for ticket persistence
5. Add update functionality to save changes
6. Implement refresh functionality to load latest data

## Outcome
A fully functional ticket builder component that enables users to create, edit, and manage tickets within the phase planner interface, with proper database persistence and real-time updates.

## Design

![image](https://github.com/user-attachments/assets/08fc864d-68dc-4bc9-86f5-7e53dba5bd86)

### UI/UX Specifications

- Text area component with associated controls
- Ticket title display showing "Ticket N" format
- Update button for saving changes
- Ticket Builder button (visual only, no action)

### Layout Details

- Text Area Size: Height 300px and ability to drag this to epand on the page. width 100% of container minus padding in line with other pages. 
- Inline placement of Ticket Builder button with title
- Update button positioned [Note: PM to specify preferred button placement]

### Database Integration

- Table: 'ticket'
- Required fields as specified in schema
- Real-time updates on content change

### Endpoints
- Endpoint for creating new ticket
- Endpoint for updating ticket content
- Endpoint for retrieving ticket data

### Interactivity
ON Click - A new test box will be added to the page.
ON Load - A Title will be generated that follows the format Ticket N where represents the sequence number of a ticket. 
ON Load - A new empty draft ticket will be created in the sphinx table 'ticket' e.g. 
```
uuid: Generate a new UUID on addition of a ticket area associated to the text box. 
feature_uuid: This should be inherited from the page URL (/feature/{UUID}/phase/{UUID}/planner -> #658)
phase_uuid: This should be inherited from the page URL (/feature/{UUID}/phase/{UUID}/planner -> #658)
name: Ticket N
sequence: interger // see above logic
dependancy: null
description: "" // start as empty string 
status: draft
created_at: timestamp
updated_at: timestamp
```
ON Load - provide a Ticket Builder Button in line with the Ticket Title (No action on Click)
ON Load - an update button which will save the current edits in the ticket area to the DB.

## Acceptance Criteria

- [ ] Component creates new ticket entry in database on load
- [ ] Ticket title displays correct sequence number
- [ ] Text area allows editing of ticket description
- [ ] Update button saves changes to database
- [ ] Content persists on page refresh
- [ ] Ticket Builder button displays inline with title (no action required)
- [ ] Component correctly inherits feature_uuid and phase_uuid from URL
- [ ] New tickets are created with correct schema and draft status
- [ ] UUID is generated for each new ticket
- [ ] Proper error handling for database operations
- [ ] Loading states are handled appropriately
- [ ] Component is responsive and maintains layout across screen sizes

**Comment by MuhammadUmer44** [comment]
@humansinstitute I can help

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?

**Comment by humansinstitute** [comment]
close not planned this was deprecated by other tickets ad PRs
