### ISSUE TITLE
Create a create a component 'ticket editor' which displays a text box when added to the screen

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#664]
## Context
We are implementing Phase 1 of the ticket management system's editing capabilities. This ticket focuses on creating a foundational component that enables users to edit ticket content with real-time updates. This component will serve as the base for all future ticket editing functionality in the system.

The implementation will establish:
- A reusable editor component
- Real-time content persistence
- Integration with the existing ticket database schema
- Foundation for future editing capabilities

## Task
1. Create new `TicketEditor` component
2. Create responsive text editing interface

## Outcome
A functional ticket editor component that:
- Renders a text input area when added to the screen
- Maintains the entered text state
- Forms a foundation for future editing capabilities

### Component Structure
```jsx
const TicketEditor = () => {
  const [content, setContent] = useState('');
  const [ticketNumber, setTicketNumber] = useState(null);

  // Component implementation
};
```

### UI/UX Specifications
- Text Area Component:
  - Height: 300px
  - Width: 100% of container (minus padding)
  - Draggable resize handle for height adjustment
  - Consistent padding with other pages
- Title Display: "Ticket N" format where N is sequential
- Control Buttons:
  - Update button (for saving changes)
  - Ticket Builder button (visual only)

### State Management
- Track current text content

## Acceptance Criteria
- [ ] Text editor renders with specified dimensions (300px height, 100% width)
- [ ] Height can be adjusted via drag handle
- [ ] Component properly integrates with existing ticket table

**Comment by aliraza556** [comment]
U
