### ISSUE TITLE
Update 'ticket editor' component - on load, register a ticket in ticket table with Ticket UUID and sequence number in database

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#669]
## Context
When opening the ticket editor component (see https://github.com/stakwork/sphinx-tribes-frontend/issues/664 and stakwork/sphinx-tribes-frontend#667), we need to register a new ticket in the database. The component has access to the feature UUID and phase UUID from the URL parameters, and needs to generate a ticket UUID to create the initial ticket record.

## Task
Modify the ticket editor component to register a new ticket when initialized, using the `/bounty/ticket/{uuid}` endpoint.

## Outcome
When the ticket editor component loads, a new ticket is registered in the database with initial values, ready for editing.

## Design
The component should:
1. Generate a ticket UUID on initialization
2. Call the `/bounty/ticket/{uuid}` endpoint with initial ticket data:

```typescript
// Initial ticket data structure
{
    uuid: string;         // Generated UUID
    feature_uuid: string; // From URL
    phase_uuid: string;   // From URL
    name: string;         // Empty
    sequence: number;     // 0
    dependency: string[]; // []
    description: string;  // Empty
    status: 'DRAFT';
    version: 1
}
```

The endpoint call will be:

```typescript
POST /bounty/ticket/{uuid}
{
    "action": "update",
    "ticket": initialTicketData
}
```

## Acceptance Criteria
- [ ] Component generates a UUID on initialization
- [ ] Component makes API call to register ticket on load
- [ ] Feature and Phase UUIDs are correctly passed from URL parameters
- [ ] Appropriate error handling is implemented for failed registration
- [ ] Successfully registered ticket UUID is stored for subsequent edits
