### ISSUE TITLE
Update 'ticket editor' component - button "Update" on click writes contents of box to db.ticket.description

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#670]
## Context
The ticket editor component needs to be enhanced to save the contents of the description text box to the database when the Update button is clicked. This will utilisee the existing `/bounty/ticket/{uuid}` endpoint to update the ticket's description while maintaining all other existing ticket data.

## Task
Add functionality to the Update button in the ticket editor component to save the description text box contents to the database.

## Outcome
When clicking the Update button, the ticket's description in the database is updated with the current contents of the text box, while preserving all other ticket data.

## Design

// The majority of ticket data would have been set already on load of the component in https://github.com/stakwork/sphinx-tribes-frontend/issues/669

{
    uuid: string;         // as previous state
    feature_uuid: string; // as previous state from URL
    phase_uuid: string;   // as previous state from URL
    name: string;         // as previous state
    sequence: number;     // as previous state
    dependency: string[]; // as previous state
    description: string;  // UPDATE based on text box entry
    status: 'DRAFT';
    version: n +1
}

### Component Update Handler

Example:

```typescript
const TicketEditor = () => {
    const [ticketData, setTicketData] = useState<Ticket | null>(null);
    const [description, setDescription] = useState('');

    const handleUpdate = async () => {
        if (!ticketData) return;

        const updatedTicket = {
            ...ticketData,
            description: description,
            version: ticketData.version + 1
        };

        const response = await fetch(`/bounty/ticket/${ticketData.uuid}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                action: 'update',
                ticket: updatedTicket
            })
        });

        if (!response.ok) {
            throw new Error('Failed to update ticket description');
        }

        // Update local state with response
        const result = await response.json();
        setTicketData(result.data);
    };

    return (
        <div>
            <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
            />
            <button onClick={handleUpdate}>Update</button>
        </div>
    );
};
```

## Acceptance Criteria
- [ ] Update button triggers save of description to database -  please show in loom video on PR
- [ ] Description from text box is correctly sent to the endpoint
- [ ] Existing ticket data is preserved during update
- [ ] Version number is incremented on each update
- [ ] Appropriate error handling for failed updates
- [ ] Success/failure feedback is shown to user via pop up
