### ISSUE TITLE
onClick of "Ticket Builder" post data to `bounty/ticket/review/send`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#671]
# Ticket Name: Implement Ticket Builder Workflow Trigger

## Context
The current system requires a mechanism to initiate a workflow when the "Ticket Builder" button is clicked. This functionality is essential for automating the process of sending ticket data to the Sphinx Tribes endpoint, which is a critical step in the ticket management process. This integration will streamline the workflow, reduce manual intervention, and ensure that ticket data is consistently and accurately transmitted to the backend system.

## Task
1. **Button Click Handling:**
   - Implement an event listener for the "Ticket Builder" button click.
   - Ensure the button is accessible and functional in each ticket component

2. **Data Preparation:**
   - Gather necessary ticket data from the frontend, ensuring all fields in the `Ticket` interface are populated.
   - Validate data to ensure it meets the required format and constraints.

3. **API Integration:**
   - Send the prepared ticket data to the Sphinx Tribes endpoint at `https://<domain>/bounty/ticket/review/send`.
   - Implement error handling for API requests, including retries and user notifications for failures.

## Outcome
Upon clicking the "Ticket Builder" button, the system will successfully send the ticket data to the specified endpoint.

## Design
  - On successful data submission, display a confirmation message to the user.
  - On failure, provide an error message with options to retry or contact support.
  - Implement data validation logic to ensure all required fields are correctly populated.
  - Develop error handling logic to manage API request failures.

  - `https://<domain>/bounty/ticket/review/send` for sending ticket data.

## Example Code
```javascript
// Example of sending ticket data on button click
document.getElementById('ticketBuilderButton').addEventListener('click', async () => {
    const ticketData = {
        uuid: '1234-5678-9101',
        feature_uuid: 'feature-uuid',
        phase_uuid: 'phase-uuid',
        name: 'Sample Ticket',
        sequence: 1,
        dependency: [],
        description: 'Detailed description of the ticket', // THIS WILL BE DRAWN FROM THE TEXT BOX
        status: 'DRAFT',
        version: 1,
        created_at: new Date(),
        updated_at: new Date()
    };

    try {
        const response = await fetch('https://<domain>/bounty/ticket/review/send', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(ticketData)
        });

        if (response.ok) {
            alert('Ticket data sent successfully!');
        } else {
            throw new Error('Failed to send ticket data');
        }
    } catch (error) {
        console.error('Error:', error);
        alert('An error occurred while sending ticket data. Please try again.');
    }
});
```

## Acceptance Criteria
- [ ] "Ticket Builder" button is functional and triggers the workflow on click.
- [ ] Ticket data is correctly formatted and sent to the specified endpoint.
- [ ] User receives feedback on the success or failure of the data submission.
- [ ] Error handling is implemented for API request failures.
- [ ] The system updates the ticket status as part of the workflow initiation.
- [ ] The feature is tested across all supported browsers and devices.

**Comment by jordan-ae** [comment]
C

**Comment by Shoaibdev7** [comment]
Hi @humansinstitute, I am on it I will make a PR today.

**Comment by Shoaibdev7** [comment]
@humansinstitute I'm just waiting for this PR to be merged (https://github.com/stakwork/sphinx-tribes-frontend/pull/673), after which I'll create my own PR since I used the interface.

**Comment by humansinstitute** [comment]
Alright I'll need it today though. This is merged now so should be no blockers. 

If you get blocked in future tag me so I know and can keep track.

**Comment by Shoaibdev7** [comment]
> Alright I'll need it today though. This is merged now so should be no blockers.
> 
> If you get blocked in future tag me so I know and can keep track.

Sure

**Comment by humansinstitute** [comment]
@Shoaibdev7 - did you get this PR done? I need this to test the feature

**Comment by Shoaibdev7** [comment]
> @Shoaibdev7 - did you get this PR done? I need this to test the feature

@humansinstitute, Please review here #675
