### ISSUE TITLE
[BUG] Update object payload to `r.Post("/{uuid}", ticketHandler.UpdateTicket)`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#679]
As per the design in https://github.com/stakwork/sphinx-tribes-frontend/issues/670

On click of Update button we generate an object to pass to `bounties/ticket/uuid` that includes 

```
{
   action: "update",
   ticket: { }
}
```

However the endpoint implementation utilised POST, GET, DELETE to differentiate the action not the action status. 

This causes a further error in `handlers/ticket.go`

```
var ticket db.Tickets
	if err := json.Unmarshal(body, &ticket); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "Error parsing request body"})
		return
}
```

Where the system attempts to Unmarshal this into the ticket struct. 

In order to rationalise this and fix. The following change will be made in the front end. 

## Task

For the `ticketEditor` component onLoad and onClick the call to the /boutnies/ticket/UUID endpoint will need to be updated to only send the `ticket` object and not `{ action: update, ticket: {}}`

```
// Initial ticket data structure
{
    uuid: string;         // Generated UUID
    feature_uuid: string; // From URL
    phase_uuid: string;   // From URL
    name: string;         // Empty
    sequence: number;     // 0
    dependency: string[]; // []
    description: string;  // Empty
    status: 'DRAFT';
    version: 1
}
```

The endpoint call will be:

```
POST /bounty/ticket/{uuid}
{
    uuid: string;                // Generated UUID
    feature_uuid: string;  // From URL
    phase_uuid: string;    // From URL
    name: string;              // Default to 'Ticket'
    sequence: number;     // 0
    dependency: string[]; // []
    description: string;  // Empty
    status: 'DRAFT';
    version: 1
}
```

## Outcome
The frontend will correctly send the `ticket` object to the backend, preventing errors during JSON unmarshalling and ensuring smooth operation of the update functionality.

## Acceptance Criteria
- [ ] The `ticketEditor` component sends only the `ticket` object in the payload on Load
- [ ] The `ticketEditor` component sends only the `ticket` object in the payload on Click of `Update`
- [ ] No errors occur in `handlers/ticket.go` related to JSON unmarshalling.
- [ ] The update functionality works seamlessly without requiring changes to the backend.
- [ ] Thorough testing is conducted to ensure no regressions in functionality.
