### ISSUE TITLE
Add a phasePlannerStore to Phase planner to manage state and refresh of tickets by webhooks

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#700]
Add a phasePlannerStore to Phase planner to manage state and refresh of tickets by webhooks

## Context
- **Need**: We need a store on the phase planenr phase to manage state across multiple ticket editor interfaces to allow us to quickly refresh components as Hive process updates tickets.
- **Background**: The `Ticket` interface already exists.

## Task
- Create phasePlannerStore
- Import phasePlannerStore to `src/people/widgetViews/PhasePlannerView.tsx`

## Outcome
A new `phasePlannerStore` interface is created, named correctly and available for use to support websocket based updates to `ticket editor` components

```
interface phasePlannerStore {
  tickets: Map<string, Ticket>;  // uuid -> Ticket
  addTicket: (ticket: Ticket) => void;
  updateTicket: (uuid: string, ticket: Partial<Ticket>) => void;
  getTicket: (uuid: string) => Ticket | undefined;
}

// EXAMPLE USAGE

function TicketComponent({ ticketId }: { ticketId: string }) {
  const ticket = useTicketStore(state => state.tickets.get(ticketId));
  
  return ticket ? <TicketDisplay ticket={ticket} /> : null;
}
```

## Acceptance Criteria
- [ ] `phasePlannerStore` interface is defined and documented.
- [ ] Names and fields are correct as specified.
- [ ] Integration with existing `Tickets` interface is correct
- [ ] import of phasePlannerStore to `src/people/widgetViews/PhasePlannerView.tsx` confirmed

**Comment by aliraza556** [comment]
l

**Comment by jordan-ae** [comment]
Please assign me

**Comment by saithsab877** [comment]
@humansinstitute Please assign me?

**Comment by Vayras** [comment]
@humansinstitute please assign

**Comment by MahtabBukhari** [comment]
d

**Comment by MuhammadUmer44** [comment]
@humansinstitute I can help?
