### ISSUE TITLE
Update the PhasePlannerStore to PhaseTicketStore 

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#704]
Update the phasePlannerStore in PR:
https://github.com/stakwork/sphinx-tribes-frontend/pull/702

## Design

To follow the logic and implementation:

```
// Main interface for Phase Tickets
interface PhaseTickets {
  [phase_uuid: string]: Ticket[];
}

export interface TicketStore {      //TicketStore -> IPhasePlannerStore
  tickets: Map<string, Ticket>;     // Map for individual tickets
  phaseTickets: PhaseTickets;       // Object for tickets by phase
  
  // Core functionality to add, update, retrieve tickets. 
  addTicket: (ticket: Ticket) => void;
  updateTicket: (uuid: string, ticket: Partial<Ticket>) => void;
  getTicket: (uuid: string) => Ticket | undefined;
  getPhaseTickets: (phase_uuid: string) => Ticket[];
}

export class PhaseTicketStore implements TicketStore {
  tickets: Map<string, Ticket> = new Map();
  phaseTickets: PhaseTickets = {};

  constructor() {
    makeAutoObservable(this);
  }

  addTicket(ticket: Ticket) {
    // Update both stores
    this.tickets.set(ticket.uuid, ticket);
    
    // Update phase grouping
    const phaseTickets = this.phaseTickets[ticket.phase_uuid] || [];
    this.phaseTickets[ticket.phase_uuid] = [...phaseTickets, ticket];
  }

  updateTicket(uuid: string, ticketUpdate: Partial<Ticket>) {
    const existingTicket = this.tickets.get(uuid);
    if (existingTicket) {
      const updatedTicket = { ...existingTicket, ...ticketUpdate };
      
      // Update both stores
      this.tickets.set(uuid, updatedTicket);
      
      // Update in phase grouping
      const phaseTickets = this.phaseTickets[existingTicket.phase_uuid] || [];
      this.phaseTickets[existingTicket.phase_uuid] = phaseTickets.map(t => 
        t.uuid === uuid ? updatedTicket : t
      );
    }
  }

  getTicket(uuid: string): Ticket | undefined {
    return this.tickets.get(uuid);
  }

  getPhaseTickets(phase_uuid: string): Ticket[] {
    return this.phaseTickets[phase_uuid] || [];
  }
}
```
## Task

- Check Names for TicketStore and PhaseTicketStore
- Implement functional methods
- Ensure getTickets, getPhaseTickets are correctly exposed. 
- Ensure Imports are correct

## Outcome
A new `PhaseTicketStore` interface is created, named correctly and available for use to support websocket based updates to `ticket editor` components

## Acceptance Criteria
- [ ] `PhaseTicketStore` interface is defined and documented.
- [ ] Names and fields are correct as specified.
- [ ] Integration with existing `Tickets` interface is correct
- [ ] import of `PhaseTicketStore` to `src/people/widgetViews/PhasePlannerView.tsx` confirmed

**Comment by aliraza556** [comment]
,

**Comment by MahtabBukhari** [comment]
f

**Comment by saithsab877** [comment]
@humansinstitute I can help?
