### ISSUE TITLE
Update the typescript interface to allow for optional fields for ticketGroup, author, authorID

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#729]
# Ticket Name: Update TypeScript Interface for Optional Fields

## Context
The existing TypeScript interface for a ticket currently requires fields that should be optional, such as `ticketGroup`, `author`, and `authorID`. This modification is necessary to align the frontend interface with backend changes that support nullable fields, allowing for more flexible ticket data management. This change is part of a broader initiative to enhance the functionality of our ticket writing and versioning. 

## Task
1. Modify the existing TypeScript interface `Ticket` to make the fields `ticketGroup`, `author`, and `authorID` optional.
2. Ensure that the implementation of this change does not disrupt existing operations or functionalities in the system.
3. Update any existing TypeScript tests to ensure they account for these optional fields.
4. Create new test cases to verify scenarios where these fields are not provided, ensuring robust coverage for edge cases.

## Outcome
The `Ticket` interface will be updated to include optional fields, providing greater flexibility in ticket data management. This will support the system in handling tickets with optional group categorization and author tracking, enhancing data adaptability.

## Design
- **Interface Changes**: Update the `Ticket` interface with the following changes:
  ```typescript
  interface Ticket {
  uuid: string;              // Still required
  ticket_group?: string;     // Optional
  feature_uuid: string;      // Still required
  phase_uuid: string;        // Still required
  name: string;              // Still required
  sequence: number;          // Still required
  dependency?: number[];     // Already optional
  description: string;       // Still required
  status: TicketStatus;      // Still required
  version?: number;          // Optional
  author?: Author;           // Optional
  author_id?: string;        // Optional
  created_at: Date;          // Still required
  updated_at: Date;          // Still required
}
  ```
- **Test Integration**:
  - Update existing tests to handle cases where `ticketGroup`, `author`, and `authorID` are both present and absent.
  - Develop new test cases specifically targeting these optional fields.

- **Note**
  - author will be either (HUMAN | AGENT) for now.
  - author_id pseudo code logic:

```
If HUMAN = author_id = user.pubkey; 
If AGENT WorkflowID-VersionID)
```

## Acceptance Criteria
- [ ] The `Ticket` interface includes the optional fields: `ticketGroup`, `author`, and `authorID`.
- [ ] No disruption to existing functionality is observed as a result of the changes.
- [ ] Updated tests are completed and pass successfully with the new interface changes.
- [ ] New test cases are implemented to ensure the functionality of the optional fields.
- [ ] The code changes are reviewed and approved by the team.
- [ ] Documentation is updated to reflect the changes in the `Ticket` interface.
- [ ] The frontend and backend data models are in sync regarding optional fields.

**Comment by saithsab877** [comment]
H

**Comment by MuhammadUmer44** [comment]
@humansinstitute I can help?

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can I help
