### ISSUE TITLE
Integrate Markdown Parsing into Chat Interface

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes-frontend#792]
# Ticket Name: Integrate Markdown Parsing into Chat Interface

## Context
The goal is to enhance the chat interface by enabling Markdown parsing, allowing users to format their messages with Markdown syntax and the replies rfom the Agents to be displayed with markdown. Code BLock Rendering will be key to this. 

This ticket will add a markdown parser to the display of tickets in the Hive Chat interface. The end goal would be to render in line styles and code blocks in a similar manner to common  AI chat apps. 

## Task
1. **Select a Markdown Parsing Library**: E.g. use `markdown-it` for its flexibility and plugin support.
2. **Integrate the Parser**: 
     - Import and initialize `markdown-it` in the chat component.
     - Parse and sanitize messages using `DOMPurify`.
3. **Update State Management**: Ensure messages are passed correctly to the chat display component.
4. **Handle User Input**: Allow users to input messages using Markdown syntax.
5. **Style the Output**: Create CSS styles for rendered Markdown correctly in the chat windows. 
7. **Test the Implementation**: Verify Markdown features and security checks.
8. **Consider Backend Security**: Ensure backend handling of messages is secure.

## Outcome
The chat interface will support Markdown, allowing for formatted messages, which are safely rendered and sanitized to prevent XSS attacks.

## Design

- **User Interactions**: Users can input and send messages using Markdown syntax.
- **Visual Requirements**: Styled Markdown content within the chat display.
- **State Changes**: Ensure state management reflects the parsed Markdown messages.
- **Logic Updates**: Integrate `markdown-it` and `DOMPurify` for parsing and sanitizing.
- **Endpoints Utilized**: No changes to backend endpoints are needed.

## Examples

Import and initialise the parser

```

// ChatDisplay.tsx
import React from 'react';
import MarkdownIt from 'markdown-it';
import DOMPurify from 'dompurify'; // To sanitize the HTML

const mdParser = new MarkdownIt({
  // You can add options here
  html: false, // Disable HTML tags in source
  linkify: true, // Autoconvert URL-like text to links
  typographer: true, // Enable smartypants and other sweet transforms
});
```

Parse and Redner Messages

```
interface ChatMessage {
  id: string;
  chat_id: string;
  message: string;
  // ... other fields
}

interface ChatDisplayProps {
  messages: ChatMessage[];
}

const ChatDisplay: React.FC<ChatDisplayProps> = ({ messages }) => {
  return (
    <div className="chat-display">
      {messages.map((msg) => {
        // Parse the Markdown content
        const rawHtml = mdParser.render(msg.message);
        // Sanitize the HTML to prevent XSS attacks
        const sanitizedHtml = DOMPurify.sanitize(rawHtml);

        return (
          <div key={msg.id} className="chat-message">
            <div
              className="message-content"
              dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
            />
          </div>
        );
      })}
    </div>
  );
};

export default ChatDisplay;
```
Explanation:

- Parsing Markdown: The markdown-it parser converts Markdown text into HTML.
- Sanitizing HTML: Using DOMPurify ensures that any HTML generated from Markdown is safe and free from malicious scripts.
- Rendering HTML: The dangerouslySetInnerHTML prop in React allows you to set HTML directly. This is necessary to render the parsed Markdown but should be used cautiously with proper sanitization.

## Acceptance Criteria
- [ ] `markdown-it` is installed and configured in the project.
- [ ] Chat messages are parsed using `markdown-it`.
- [ ] HTML output is sanitized with `DOMPurify`.
- [ ] Messages are rendered as HTML in the chat display component.
- [ ] CSS styles applied to Markdown elements.
- [ ] Messages maintain state throughout the application.
- [ ] Markdown features like headings, lists, and links render correctly.
- [ ] Backend stores raw Markdown without alteration.

**Comment by Ekep-Obasi** [comment]
A
